xcodeproj 'Roaming.xcodeproj'
platform :ios, '7.0'
pod 'FMDB', '~> 2.5'
pod 'CocoaLumberjack', '~> 2.0.0' 
pod 'SIAlertView', '~> 1.3'
pod 'ReactiveCocoa', '~>  2.5'
pod 'CocoaAsyncSocket', '~> 7.4.1'
pod 'AFNetworking', '~> 2.6.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Toast', '~> 2.4'
pod 'ZipArchive', '~> 1.4.0'
pod 'skpsmtpmessage', '~> 0.0.1'